/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\src\assets\models\uploads_files_3576635_loft.glb 
*/

import React, { useCallback, useState } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { Selection, Select, EffectComposer, Outline } from "@react-three/postprocessing";
import { debounce } from "lodash";

export function House() {
  const [hovered, setHovered] = useState(null);

  const { nodes, materials } = useGLTF("/models/House.glb");
  const debouncedHover = useCallback(debounce(setHovered, 30), []);
  const over = (name) => (e) => (e.stopPropagation(), debouncedHover(name), console.log(e));

  const price = { KNOXHULT: 5999, BRÖNDEN: 433, SKAFTET: 77, FANBYN: 255, VOXLÖV: 1699, LIVSVERK: 44 }[hovered] ?? 5999;
  return (
    <>
      <Selection>
        <EffectComposer multisampling={8} autoClear={false}>
          <Outline blur visibleEdgeColor="green" edgeStrength={100} width={1000} />
        </EffectComposer>
        <group dispose={null}>
          <mesh
            geometry={nodes.Cube004.geometry}
            material={nodes.Cube004.material}
            position={[-0.186, 5.775, -3.966]}
          />
          <mesh
            geometry={nodes.Cube046.geometry}
            material={nodes.Cube046.material}
            position={[0.05, 5.575, -2.732]}
            scale={[0.983, 1, 0.986]}
          />
          <group position={[-0.233, 5.546, -5.65]}>
            <mesh geometry={nodes.Cube066_1.geometry} material={nodes.Cube066_1.material} />
            <mesh geometry={nodes.Cube066_2.geometry} material={materials.luz} />
          </group>
          <group position={[-0.594, 2.761, -0.946]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]}>
            <mesh geometry={nodes.Cylinder_1.geometry} material={materials["metal 1"]} />
            <mesh geometry={nodes.Cylinder_2.geometry} material={materials.luz} />
          </group>
          <group position={[-2.3, 5.546, -5.65]}>
            <mesh geometry={nodes.Cube087.geometry} material={nodes.Cube087.material} />
            <mesh geometry={nodes.Cube087_1.geometry} material={materials.luz} />
          </group>
          <mesh geometry={nodes.Cube039.geometry} material={materials.luz} position={[-2.385, 4.321, -2.723]} />
          <group position={[-2.999, 2.81, -2.55]}>
            <mesh geometry={nodes.Cube025_1.geometry} material={nodes.Cube025_1.material} />
            <mesh geometry={nodes.Cube025_2.geometry} material={materials.vidro} />
          </group>
          <group position={[0.067, 2.904, -4.025]}>
            <mesh geometry={nodes.Cube003_1.geometry} material={nodes.Cube003_1.material} />
            <mesh geometry={nodes.Cube003_2.geometry} material={materials["piso "]} />
          </group>
          <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[0.337, 2.713, -4.988]} />
          <mesh geometry={nodes.Cube044.geometry} material={materials.metal} position={[0.181, 3.786, -3.533]} />
          <mesh
            geometry={nodes.Cube029.geometry}
            material={materials.luz}
            position={[0.775, 2.298, -5.441]}
            scale={[0.02, 0.002, 1]}
          />
          <group position={[-2.3, 2.696, -5]}>
            <mesh geometry={nodes.Cube046_1.geometry} material={nodes.Cube046_1.material} />
            <mesh geometry={nodes.Cube046_2.geometry} material={materials.luz} />
          </group>
          <mesh geometry={nodes.Cube016.geometry} material={materials["tecido 2"]} position={[-0.7, 3.125, -3.925]} />
          <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[2.334, 4.15, -6.983]} />
          <mesh geometry={nodes.Cube040.geometry} material={materials.madeira} position={[-0.7, 3.025, -3.925]} />
          <mesh geometry={nodes.Cube041.geometry} material={materials["tecido 1"]} position={[-0.684, 3.276, -3.925]} />
          <group position={[0.648, 3.967, -3.908]}>
            <mesh geometry={nodes.Cube049_1.geometry} material={materials["mdf branco"]} />
            <mesh geometry={nodes.Cube049_2.geometry} material={materials["pedra 1"]} />
            <mesh geometry={nodes.Cube049_3.geometry} material={materials["mdf cinza"]} />
            <mesh geometry={nodes.Cube049_4.geometry} material={materials.luz} />
          </group>
          <mesh geometry={nodes.Cube015.geometry} material={materials["tecido 2"]} position={[0.3, 3.45, -3.925]} />
          <group position={[-0.081, 3.296, -3.925]} rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.Cube056_1.geometry} material={nodes.Cube056_1.material} />
            <mesh geometry={nodes.Cube056_2.geometry} material={materials["pedra 1"]} />
          </group>
          <mesh geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} position={[2.258, 4.342, -6.815]} />
          <Select
            enabled={hovered === "SKAFTET"}
            onPointerOver={over("SKAFTET")}
            onPointerOut={() => debouncedHover(null)}
          >
            <mesh
              geometry={nodes.Cube001.geometry}
              material={nodes.Cube001.material}
              position={[-0.021, 1.5, -3.969]}
            />
          </Select>
          <mesh geometry={nodes.Cube053.geometry} material={materials["piso "]} position={[-0.021, 1.5, -3.969]} />
          <Select
            enabled={hovered === "BRÖNDEN"}
            onPointerOver={over("BRÖNDEN")}
            onPointerOut={() => debouncedHover(null)}
          >
            <mesh geometry={nodes.Cube054.geometry} material={materials.concreto} position={[-5.1, 1.175, -3.507]} />
          </Select>
          <group position={[-4.767, 0.05, -4.438]}>
            <mesh geometry={nodes.Cube077.geometry} material={materials["piso "]} />
            <mesh geometry={nodes.Cube077_1.geometry} material={materials.grama} />
          </group>
          <mesh geometry={nodes.Cube058.geometry} material={materials["piso "]} position={[-4.606, 0.15, -4.497]} />
          <mesh geometry={nodes.Cube070.geometry} material={nodes.Cube070.material} position={[3.1, 1.5, -0.014]} />
          <mesh geometry={nodes.Cube071.geometry} material={materials["pedra 1"]} position={[3.1, 4.075, -0.014]} />
          <group position={[3.065, 1.492, 0.351]} rotation={[0, 0.044, 0]} scale={[1, 0.998, 0.992]}>
            <mesh geometry={nodes.Cube096.geometry} material={nodes.Cube096.material} />
            <mesh geometry={nodes.Cube096_1.geometry} material={materials.metal} />
          </group>
          <mesh geometry={nodes.Cube.geometry} material={materials["piso "]} position={[-0.186, 0.075, -3.966]} />
          <mesh geometry={nodes.Cube005.geometry} material={materials["pedra 1"]} position={[-1.489, 1.056, -5.886]} />
          <mesh geometry={nodes.Cube007.geometry} material={materials["pedra 1"]} position={[-0.969, 0.738, -4.1]} />
          <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[0.4, 1.095, -5.825]} />
          <group position={[-1.177, 2.125, -5.788]}>
            <mesh geometry={nodes.Cube014_1.geometry} material={nodes.Cube014_1.material} />
            <mesh geometry={nodes.Cube014_2.geometry} material={materials.luz} />
            <mesh geometry={nodes.Cube014_3.geometry} material={nodes.Cube014_3.material} />
          </group>
          <mesh
            geometry={nodes.Cube018.geometry}
            material={materials.madeira}
            position={[-0.451, 0.6, -4.531]}
            rotation={[0, -0.087, 0]}
          />
          <mesh
            geometry={nodes.Cube023.geometry}
            material={materials.madeira}
            position={[-1.304, 0.6, -3.521]}
            rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
          />
          <mesh
            geometry={nodes.Cube026.geometry}
            material={materials.madeira}
            position={[-0.45, 0.6, -3.669]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            geometry={nodes.Cube020.geometry}
            material={materials["tecido 1"]}
            position={[-0.451, 0.623, -4.519]}
            rotation={[0, -0.087, 0]}
          />
          <mesh
            geometry={nodes.Cube024.geometry}
            material={materials["tecido 1"]}
            position={[-1.297, 0.623, -3.53]}
            rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
          />
          <mesh
            geometry={nodes.Cube027.geometry}
            material={materials["tecido 1"]}
            position={[-0.451, 0.623, -3.681]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            geometry={nodes.Cube028.geometry}
            material={materials["mdf cinza"]}
            position={[-1.475, 0.587, -5.646]}
          />
          <mesh geometry={nodes.Cube012.geometry} material={materials["metal 1"]} position={[0.4, 1.055, -4.223]} />
          <mesh geometry={nodes.Cube021.geometry} material={materials.madeira} position={[-1.147, 0.6, -4.531]} />
          <mesh
            geometry={nodes.Cube022.geometry}
            material={materials["tecido 1 var"]}
            position={[-1.146, 0.623, -4.519]}
          />
          <mesh geometry={nodes.Sphere002.geometry} material={materials.metal} position={[-0.769, 0.95, -4.03]} />
          <group position={[-0.652, 1.614, -4.1]}>
            <mesh geometry={nodes.Cube007_1.geometry} material={materials["metal 1"]} />
            <mesh geometry={nodes.Cube007_2.geometry} material={materials.luz} />
          </group>
          <mesh geometry={nodes.Cylinder003.geometry} material={materials.metal} position={[-2.638, 1.139, -6.046]} />
          <group position={[0.235, 1.223, -5.594]}>
            <mesh geometry={nodes.Cube042_1.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cube042_2.geometry} material={materials["metal 1"]} />
            <mesh geometry={nodes.Cube042_3.geometry} material={materials["metal 2"]} />
            <mesh geometry={nodes.Cube042_4.geometry} material={materials.luz} />
          </group>
          <mesh
            geometry={nodes.Cube032.geometry}
            material={materials.metal}
            position={[-1.47, 1.332, -5.965]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh geometry={nodes.Cylinder.geometry} material={materials.metal} position={[0.398, 1.87, -4.225]} />
          <mesh geometry={nodes.Cube073.geometry} material={materials["mdf cinza"]} position={[0.4, 0.58, -4.1]} />
          <group position={[0.4, 0.797, -4.481]}>
            <mesh geometry={nodes.Cube100.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cube100_1.geometry} material={materials["metal 1"]} />
            <mesh geometry={nodes.Cube100_2.geometry} material={materials["metal 2"]} />
            <mesh geometry={nodes.Cube100_3.geometry} material={materials.luz} />
          </group>
          <mesh
            geometry={nodes.Cube006.geometry}
            material={materials["piso "]}
            position={[2.5, 1.551, -2.982]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <group position={[2.278, 1.164, -4.259]}>
            <mesh geometry={nodes.Cube034_1.geometry} material={nodes.Cube034_1.material} />
            <mesh geometry={nodes.Cube034_2.geometry} material={materials.luz} />
            <mesh geometry={nodes.Cube034_3.geometry} material={materials["mdf cinza"]} />
          </group>
          <mesh
            geometry={nodes.Cube031.geometry}
            material={materials["piso "]}
            position={[2.99, 1.599, -2.932]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh geometry={nodes.Cube047.geometry} material={materials.metal} position={[2.925, 2.466, -2.979]} />
          <mesh
            geometry={nodes.Cube025.geometry}
            material={materials["tecido 1"]}
            position={[-0.886, 0.442, -2.241]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh geometry={nodes.Cube013.geometry} material={materials.madeira} position={[-1.23, 0.2, -2.055]} />
          <group position={[-2.125, 0.467, -0.36]} rotation={[-Math.PI, Math.PI / 3, -Math.PI]}>
            <mesh geometry={nodes.Cube071_1.geometry} material={materials["tecido 1"]} />
            <mesh geometry={nodes.Cube071_2.geometry} material={materials.madeira} />
          </group>
          <group position={[-2.225, 3.315, -5.508]} rotation={[0, Math.PI / 3, 0]}>
            <mesh geometry={nodes.Cube071_1.geometry} material={materials["tecido 1"]} />
            <mesh geometry={nodes.Cube071_2.geometry} material={materials.madeira} />
          </group>
          <mesh geometry={nodes.Cube034.geometry} material={materials.madeira} position={[0.75, 0.209, -0.614]} />
          <mesh geometry={nodes.Cube035.geometry} material={materials["tecido 1"]} position={[0.75, 0.209, -0.614]} />
          <mesh geometry={nodes.Cube036.geometry} material={materials["tecido 2"]} position={[-0.75, 0.153, -0.664]} />
          <group position={[-0.45, 0.305, -0.714]}>
            <mesh geometry={nodes.Cube019_1.geometry} material={materials.madeira} />
            <mesh geometry={nodes.Cube019_2.geometry} material={materials["pedra 1"]} />
          </group>
          <group position={[-1.364, 0.724, -2.281]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube065_1.geometry} material={materials["tecido 3"]} />
            <mesh geometry={nodes.Cube065_2.geometry} material={materials["tecido 2"]} />
          </group>
          <mesh
            geometry={nodes.Cube059.geometry}
            material={materials["tecido 2"]}
            position={[-2.027, 0.711, -0.229]}
            rotation={[-0.158, 1.37, -0.042]}
          />
          <mesh
            geometry={nodes.Cube060.geometry}
            material={materials["tecido 2"]}
            position={[-2.309, 3.563, -5.51]}
            rotation={[0.012, -0.547, -0.216]}
          />
          <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-0.248, 4.438, -3.86]} />
          <mesh geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} position={[-1.025, 4.35, -6.12]} />
          <mesh
            geometry={nodes["3DGeom~1_Defintion"].geometry}
            material={materials.porcelana}
            position={[-2.826, 3.056, -0.145]}
            rotation={[0, 1.551, 0]}
            scale={[0.039, 0.113, 0.066]}
          />
          <mesh
            geometry={nodes["3DGeom~1_Defintion001"].geometry}
            material={materials.porcelana}
            position={[-2.826, 3.056, -1.874]}
            rotation={[0, 1.551, 0]}
            scale={[0.047, 0.113, 0.066]}
          />
          <mesh
            geometry={nodes["3DGeom~1_Defintion002"].geometry}
            material={materials.porcelana}
            position={[-2.828, 4.545, -3.35]}
            rotation={[0, 1.551, 0]}
            scale={[0.047, 0.113, 0.066]}
          />
          <mesh
            geometry={nodes["3DGeom~1_Defintion003"].geometry}
            material={materials.porcelana}
            position={[-2.828, 4.545, -5.375]}
            rotation={[0, 1.551, 0]}
            scale={[0.055, 0.113, 0.066]}
          />
          <mesh
            geometry={nodes["3DGeom~1_Defintion004"].geometry}
            material={materials.porcelana}
            position={[-2.819, 1.7, -4.933]}
            rotation={[0, 1.551, 0]}
            scale={[0.03, 0.113, 0.066]}
          />
          <group position={[-0.16, 3.504, -3.953]}>
            <mesh geometry={nodes.Cube027_1.geometry} material={materials["tecido 3"]} />
            <mesh geometry={nodes.Cube027_2.geometry} material={materials["tecido 2"]} />
          </group>
          <mesh geometry={nodes.Cube055.geometry} material={materials.madeira} position={[-1.92, 3.059, -3.933]} />
          <mesh geometry={nodes.Cube056.geometry} material={materials["tecido 1"]} position={[-1.92, 3.163, -3.933]} />
          <mesh
            geometry={nodes.Cylinder002.geometry}
            material={materials["pedra 1"]}
            position={[-2.547, 3.2, -4.748]}
          />
          <mesh
            geometry={nodes.Plane.geometry}
            material={materials["tecido 3"]}
            position={[-1.007, 3.352, -3.935]}
            rotation={[0, 0, -1.098]}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6150.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, 0.212]}
            rotation={[0.553, -0.647, 0.353]}
            scale={0.739}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6001.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -0.492]}
            rotation={[2.313, -0.966, 2.407]}
            scale={0.566}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6002.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -1.124]}
            rotation={[2.705, -0.134, 3.076]}
            scale={0.849}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6003.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -3.112]}
            rotation={[2.589, 0.647, -2.789]}
            scale={0.651}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6004.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -2.493]}
            rotation={[0.829, 0.966, -0.734]}
            scale={0.616}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6005.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -1.935]}
            rotation={[0.436, 0.134, -0.065]}
            scale={0.726}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6006.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -3.849]}
            rotation={[0.553, -0.647, 0.353]}
            scale={0.739}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6007.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -4.553]}
            rotation={[2.313, -0.966, 2.407]}
            scale={0.566}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6008.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -5.185]}
            rotation={[2.705, -0.134, 3.076]}
            scale={0.849}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6009.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -7.205]}
            rotation={[2.589, 0.647, -2.789]}
            scale={0.675}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6010.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -6.563]}
            rotation={[0.829, 0.966, -0.734]}
            scale={0.516}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6011.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -5.985]}
            rotation={[0.436, 0.134, -0.065]}
            scale={0.775}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6012.geometry}
            material={materials["planta 8"]}
            position={[-4.819, 0.066, -6.464]}
            rotation={[0.553, -0.647, 0.353]}
            scale={0.882}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6013.geometry}
            material={materials["planta 8"]}
            position={[-4.819, 0.066, -7.304]}
            rotation={[2.313, -0.966, 2.407]}
            scale={0.675}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6014.geometry}
            material={materials["planta 8"]}
            position={[-4.132, 0.066, -7.304]}
            rotation={[1.699, 1.135, -1.715]}
            scale={0.659}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6015.geometry}
            material={materials["planta 8"]}
            position={[-4.132, 0.066, -6.464]}
            rotation={[0.456, 0.315, -0.154]}
            scale={0.822}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6016.geometry}
            material={materials["planta 8"]}
            position={[-3.275, 0.066, -7.304]}
            rotation={[0.456, 0.311, -0.152]}
            scale={0.741}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6017.geometry}
            material={materials["planta 8"]}
            position={[-3.275, 0.066, -6.464]}
            rotation={[0.449, -0.267, 0.123]}
            scale={0.693}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6018.geometry}
            material={materials["planta 8"]}
            position={[-3.324, 0.066, -6.908]}
            rotation={[0.553, -0.647, 0.353]}
            scale={0.675}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6019.geometry}
            material={materials["planta 8"]}
            position={[-4.083, 0.066, -6.809]}
            rotation={[0.829, 0.966, -0.734]}
            scale={0.675}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6020.geometry}
            material={materials["planta 8"]}
            position={[-4.77, 0.066, -6.809]}
            rotation={[1.443, -1.135, 1.426]}
            scale={0.659}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6021.geometry}
            material={materials["planta 8"]}
            position={[-5.626, 0.066, -6.809]}
            rotation={[2.686, -0.311, 2.99]}
            scale={0.741}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6022.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -5.464]}
            rotation={[2.589, 0.647, -2.789]}
            scale={0.739}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6023.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -4.76]}
            rotation={[0.829, 0.966, -0.734]}
            scale={0.566}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6024.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -4.127]}
            rotation={[0.436, 0.134, -0.065]}
            scale={0.849}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6025.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -2.139]}
            rotation={[0.553, -0.647, 0.353]}
            scale={0.651}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6026.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -2.759]}
            rotation={[2.313, -0.966, 2.407]}
            scale={0.498}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6027.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -3.316]}
            rotation={[2.705, -0.134, 3.076]}
            scale={0.748}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6028.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -1.403]}
            rotation={[2.589, 0.647, -2.789]}
            scale={0.739}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6029.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -0.699]}
            rotation={[0.829, 0.966, -0.734]}
            scale={0.566}
          />
          <mesh
            geometry={nodes.majid_bush_1_p6030.geometry}
            material={materials["planta 8"]}
            position={[-5.577, 0.066, -0.066]}
            rotation={[0.436, 0.134, -0.065]}
            scale={0.849}
          />
          <group position={[0.112, 3.644, -2.956]} rotation={[1.43, -0.188, 2.459]} scale={[0.006, 0.007, 0.01]}>
            <mesh geometry={nodes["3DGeom~26_Defintion_1"].geometry} material={materials["planta 7"]} />
            <mesh geometry={nodes["3DGeom~26_Defintion_2"].geometry} material={materials["planta 6"]} />
            <mesh geometry={nodes["3DGeom~26_Defintion_3"].geometry} material={materials["planta 5"]} />
            <mesh geometry={nodes["3DGeom~26_Defintion_4"].geometry} material={materials["planta 4"]} />
          </group>
          <group position={[-0.229, 1.344, -5.942]} rotation={[-0.002, -1.496, -0.045]} scale={[0.008, 0.013, 0.008]}>
            <mesh geometry={nodes["3DGeom~36_Defintion_1"].geometry} material={materials["planta 1"]} />
            <mesh geometry={nodes["3DGeom~36_Defintion_2"].geometry} material={materials["planta 2"]} />
          </group>
          <group position={[-0.816, 0.678, -0.438]} rotation={[-1.801, 1.046, -0.952]} scale={[-0.01, -0.011, -0.012]}>
            <mesh geometry={nodes["3DGeom~42_Defintion_1"].geometry} material={materials["planta 3"]} />
            <mesh geometry={nodes["3DGeom~42_Defintion_2"].geometry} material={materials["planta 2"]} />
          </group>
          <group position={[-0.802, 0.404, -0.437]} scale={[1, 1.5, 1]}>
            <mesh geometry={nodes.Cylinder011.geometry} material={materials.agua} />
            <mesh geometry={nodes.Cylinder011_1.geometry} material={materials["vidro 2"]} />
          </group>
          <mesh
            geometry={nodes.Cube061.geometry}
            material={materials.porcelana}
            position={[-2.623, 3.5, -4.791]}
            rotation={[0, Math.PI / 4, 0]}
          />
          <group position={[0.115, 3.45, -2.968]} scale={[1, 1.5, 1]}>
            <mesh geometry={nodes.Cylinder012.geometry} material={materials.agua} />
            <mesh geometry={nodes.Cylinder012_1.geometry} material={materials["vidro 2"]} />
          </group>
          <group position={[-0.231, 0.908, -5.939]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[1, 1.5, 1]}>
            <mesh geometry={nodes.Cylinder013.geometry} material={materials.agua} />
            <mesh geometry={nodes.Cylinder013_1.geometry} material={materials["vidro 2"]} />
          </group>
          <mesh geometry={nodes.Cube062.geometry} material={materials["mdf cinza"]} position={[-0.121, 0.475, 0.525]} />
          <mesh geometry={nodes.Cube063.geometry} material={materials["pedra 1"]} position={[-1.847, 3.326, 0.536]} />
          <group position={[-0.149, 2.102, 0.536]}>
            <mesh geometry={nodes.Cube084.geometry} material={nodes.Cube084.material} />
            <mesh geometry={nodes.Cube084_1.geometry} material={materials.luz} />
          </group>
          <mesh geometry={nodes.Cube066.geometry} material={materials.metal} position={[-1.847, 0.692, 0.536]} />
          <mesh
            geometry={nodes.Cube068.geometry}
            material={materials["plastico preto"]}
            position={[-0.149, 1.655, 0.363]}
          />
          <group position={[1.201, 3.471, -3.637]} rotation={[0, -Math.PI / 4, 0]}>
            <mesh geometry={nodes.Cylinder017.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder017_1.geometry} material={materials["mdf branco"]} />
            <mesh geometry={nodes.Cylinder017_2.geometry} material={materials["tecido 1"]} />
          </group>
          <mesh
            geometry={nodes.Cube065.geometry}
            material={materials["mdf cinza"]}
            position={[-1.092, 0.467, 0.268]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            geometry={nodes.Cube069.geometry}
            material={materials["mdf cinza"]}
            position={[-0.51, 0.467, 0.33]}
            rotation={[0, -0.262, 0]}
          />
        </group>
        <Text position={[1, 1.25, 0]} rotation={[0, Math.PI, 0]} color="black" fontSize={0.15} letterSpacing={-0.05}>
          {hovered ? hovered : "LIVINGROOM"}
        </Text>
        {/** Forward the price to the ticker component */}
        {/* <Price value={price} position={[-2, 0.3, -3.25]} /> */}
      </Selection>
    </>
  );
}

useGLTF.preload("/models/House.glb");
